"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TRI_TO_ID = exports.ID_TO_TRI = exports.ID_TO_NAME = exports.TRI_TO_NAME = void 0;
exports.TRI_TO_NAME = {
    ATL: 'Atlanta Hawks',
    BOS: 'Boston Celtics',
    BKN: 'Brooklyn Nets',
    CHA: 'Charlotte Hornets',
    CHI: 'Chicago Bulls',
    CLE: 'Cleveland Cavaliers',
    DAL: 'Dallas Mavericks',
    DEN: 'Denver Nuggets',
    DET: 'Detroit Pistons',
    GSW: 'Golden State Warriors',
    HOU: 'Houston Rockets',
    IND: 'Indiana Pacers',
    LAC: 'Los Angeles Clippers',
    LAL: 'Los Angeles Lakers',
    MEM: 'Memphis Grizzlies',
    MIA: 'Miami Heat',
    MIL: 'Milwaukee Bucks',
    MIN: 'Minnesota Timberwolves',
    NOP: 'New Orleans Pelicans',
    NYK: 'New York Knicks',
    OKC: 'Oklahoma City Thunder',
    ORL: 'Orlando Magic',
    PHI: 'Philadelphia 76ers',
    PHX: 'Phoenix Suns',
    POR: 'Portland Trail Blazers',
    SAC: 'Sacramento Kings',
    SAS: 'San Antonio Spurs',
    TOR: 'Toronto Raptors',
    UTA: 'Utah Jazz',
    WAS: 'Washington Wizards',
};
exports.ID_TO_NAME = {
    1: 'Atlanta Hawks',
    2: 'Boston Celtics',
    3: 'Brooklyn Nets',
    4: 'Charlotte Hornets',
    5: 'Chicago Bulls',
    6: 'Cleveland Cavaliers',
    7: 'Dallas Mavericks',
    8: 'Denver Nuggets',
    9: 'Detroit Pistons',
    10: 'Golden State Warriors',
    11: 'Houston Rockets',
    12: 'Indiana Pacers',
    13: 'Los Angeles Clippers',
    14: 'Los Angeles Lakers',
    15: 'Memphis Grizzlies',
    16: 'Miami Heat',
    17: 'Milwaukee Bucks',
    18: 'Minnesota Timberwolves',
    19: 'New Orleans Pelicans',
    20: 'New York Knicks',
    21: 'Oklahoma City Thunder',
    22: 'Orlando Magic',
    23: 'Philadelphia 76ers',
    24: 'Phoenix Suns',
    25: 'Portland Trail Blazers',
    26: 'Sacramento Kings',
    27: 'San Antonio Spurs',
    28: 'Toronto Raptors',
    29: 'Utah Jazz',
    30: 'Washington Wizards',
};
exports.ID_TO_TRI = {
    1: 'ATL',
    2: 'BOS',
    3: 'BKN',
    4: 'CHA',
    5: 'CHI',
    6: 'CLE',
    7: 'DAL',
    8: 'DEN',
    9: 'DET',
    10: 'GSW',
    11: 'HOU',
    12: 'IND',
    13: 'LAC',
    14: 'LAL',
    15: 'MEM',
    16: 'MIA',
    17: 'MIL',
    18: 'MIN',
    19: 'NOP',
    20: 'NYK',
    21: 'OKC',
    22: 'ORL',
    23: 'PHI',
    24: 'PHX',
    25: 'POR',
    26: 'SAC',
    27: 'SAS',
    28: 'TOR',
    29: 'UTA',
    30: 'WAS',
};
exports.TRI_TO_ID = Object.entries(exports.ID_TO_TRI).reduce((acc, [id, tri]) => {
    acc[tri] = Number(id);
    return acc;
}, {});
